import {TokenType} from "./TokenType";

export const KEYWORDS: Record<string, TokenType> = {
	class: TokenType.CLASS,
	else: TokenType.ELSE,
	false: TokenType.FALSE,
	for: TokenType.FOR,
	function: TokenType.FUNCTION,
	if: TokenType.IF,
	null: TokenType.NULL,
	print: TokenType.PRINT,
	return: TokenType.RETURN,
	super: TokenType.SUPER,
	this: TokenType.THIS,
	true: TokenType.TRUE,
	var: TokenType.VAR,
	const: TokenType.CONST,
	abstract: TokenType.ABSTRACT,
	public: TokenType.PUBLIC,
	protected: TokenType.PROTECTED,
	private: TokenType.PRIVATE,
	override: TokenType.OVERRIDE,
	static: TokenType.STATIC,
	constructor: TokenType.CONSTRUCTOR,
	extends: TokenType.EXTENDS,
	import: TokenType.IMPORT,
	export: TokenType.EXPORT,
	as: TokenType.AS,
	string: TokenType.STRING_TYPE,
	number: TokenType.NUMBER_TYPE,
	bool: TokenType.BOOL_TYPE,
};